### ISSUE TITLE
Image not build correctly in Github Actions

### ISSUE THREAD

**Issue by TheisFerre** [bentoml/aws-sagemaker-deploy#39]
This issue originates from an [issue](https://github.com/bentoml/bentoctl/issues/159) in the Bentoctl repository. I later found out it was more related to the aws-sagemaker operator and I have therefore moved the issue.

When building the docker image with `bentoctl build` in Github Actions, the `PATH` environment variable is not set correctly. See screenshot below from docker image that has been build with Github Actions:
![image](https://user-images.githubusercontent.com/37203334/170650975-01989ec9-a0db-42d4-bc16-275c44d6586c.png)

If i build the docker image locally instead, the `PATH` environment variable is set correctly. I.e. this problem only occurs when using Github Actions.

To fix it, I added the following line to the `Dockerfile.template` file: `RUN echo \"export PATH=$%s:$%s\" >> /root/.bashrc' "BENTO_PATH" "PATH"`. A longer-term solution would be to find the root cause of this issue, and maybe rewrite the `Dockerfile.Template` file, such that it also works in Github Actions.

# To reproduce:

**Step 1 - package versions**

bentoml==1.0.0a7
bentoctl==0.2.2
aws-sagemaker-deploy==v0.1.0

**Step 2 - building the bento**

Model is saved as a MLFlow model (scikit-learn).

I build the bento with the following bentofile `bentoml build -f bentofile.yml`

```
# bentofile.yml
service: "service.py:svc"
include:
 - "*.py" 
python:
  packages:
   - scikit-learn
   - pandas
   - mlflow
docker:
  distro: debian
  gpu: False
  python_version: "3.8.9"
```

**Step 3 - containerize bento, i.e. build image with  `bentoctl` and `aws-sagemaker operator`**

I containerize with the following deployment_config.yml file `bentoctl build -b model:latest -f deployment_config.yml --dry-run`

```
# deployment_config.yml
api_version: v1
name: my-model
operator:
  name: aws-sagemaker
template: terraform
spec:
  region: eu-central-1
  instance_type: ml.t2.medium
  initial_instance_count: 1
  timeout: 60
  initial_sampling_percentage: 1
```
