### ISSUE TITLE
Could not find files declared in bentofile.yaml include

### ISSUE THREAD

**Issue by renzpaoloabergos** [bentoml/aws-sagemaker-deploy#43]
Hi! I was able to deploy to AWS Sagemaker but model could not initialize (or be used) because it could not find the files that I specified in `bentofile.yaml -> include -> "*.pyx"` 

```
service: "service:svc" # Same as the argument passed to `bentoml serve`
labels:
  owner: renz
  stage: prod
include:
  - "*.py" # A pattern for matching which files to include in the bento
  - "*.pyx"
python:
  packages: # Additional pip packages required by the service
    - boto3
    - ...
```

Everything works fine when using `bentoml serve` and `docker run`.

I think that the files are not copied when creating the deployable or it's in a different directory (?). I tried listing the files in directory during runtime (`os.listdir('.')`) but the files (`*.pyx`) aren't there, only these:
```
FILES IN DIR: ['sagemaker_service.py', 'serve', 'README.md', 'bento.yaml']
```
